from analyzing import BIT
[
  [BIT('div',{'id': 'statsPanel'},[])],
  [BIT('div',{'id': 'perksPanel'},[])],
  [BIT('div',{'id': 'achievePanel'},[])],
  [BIT('b-tooltip',{':label': "flair('${achievement}')", 'position': 'is-bottom', 'size': 'is-small', 'animated': None},[BIT('div',{'class': 'achievement'},[BIT('span',{'class': 'has-text-warning'},["'${achievements[achievement].name}'"]), BIT('span',{},["'${achievements[achievement].desc}'"]), "'${emblem}'"])])],
  [BIT('b-tooltip',{':label': "feat('fool')", 'position': 'is-bottom', 'size': 'is-small', 'animated': None},[BIT('div',{'id': 'thefool', 'class': 'achievement'},[BIT('span',{'class': 'has-text-danger'},["'${feats.fool.name}'"]), BIT('span',{},['"${loc(\'feat_fool_spoof\')}"'])])])],
  [BIT('p',{'class': 'flair', 'title': '${sLevel(global.stats.feat[feat])} ${loc(baseIcon)}'},[BIT('svg',{'class': 'star${global.stats.feat[feat]}', 'version': '1.1', 'x': '0px', 'y': '0px', 'width': '16px', 'height': '16px', 'viewbox': '${svgViewBox(baseIcon)}', 'xml:space': 'preserve'},["'${svgIcons(baseIcon)}'"])])],
  [BIT('b-tooltip',{':label': "feat('${feat}')", 'position': 'is-bottom', 'size': 'is-small', 'animated': None},[BIT('div',{'class': 'achievement'},[BIT('span',{'class': 'has-text-danger'},["'${feats[feat].name}'"]), BIT('span',{},["'${feats[feat].desc}'"]), "'${star}'"])])],
  [BIT('div',{'class': 'has-text-warning'},['\'${loc("achieve_draw_achieve_earned",[earned,total])}${trick}\''])],
  [BIT('span',{'class': 'flair'},[BIT('svg',{'class': 'star${a_level}', 'version': '1.1', 'x': '0px', 'y': '0px', 'width': '16px', 'height': '16px', 'viewbox': '${svgViewBox(bIcon)}', 'xml:space': 'preserve'},["'${svgIcons(bIcon)}'"])])],
  [BIT('div',{},['"${loc(\'evo_challenge_plasmid\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_mastery\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_trade\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_craft\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_crispr\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_nerfed\')}"'])],
  [BIT('div',{},['"${loc(\'evo_challenge_badgenes\')}"'])],
  [BIT('div',{'class': 'is-sr-only'},[BIT('div',{},["'Active Challenge Genes'"]), "'${desc}'"])],
  [BIT('div',{'id': 'topbarPlanet'},[])],
  [BIT('span',{'class': 'row'},[BIT('span',{'class': 'has-text-caution'},["'${universe_types[universe].name}'"]), "':\\n                        '", BIT('span',{},['"${loc(\'perks_mastery_general\',[`"', BIT('span',{'class': 'has-text-advanced'},["'${+(mastery.g).toFixed(2)}%'"]), "'`])}\\n                        '"])])],
  [BIT('span',{'class': 'row'},[BIT('span',{'class': 'has-text-caution'},["'${universe_types[universe].name}'"]), "':\\n                        '", BIT('span',{},['"\\n                            ${loc(\'perks_mastery_general\',[`"', BIT('span',{'class': 'has-text-advanced'},["'${+(mastery.g).toFixed(2)}%'"]), '"`])},\\n                            ${loc(\'perks_mastery_universe\',[`"', BIT('span',{'class': 'has-text-advanced'},["'${+(mastery.u).toFixed(2)}%'"]), '"`])},\\n                            ${loc(\'perks_mastery_total\',[`"', BIT('span',{'class': 'has-text-advanced'},["'${+(mastery.g+mastery.u).toFixed(2)}%'"]), "'`])}\\n                        '"])])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_unlocked_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_blackhole_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_blackhole_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_trade_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_trade_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_creator_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_creator_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_mass_extinction_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_mass_extinction_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_doomed_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_explorer_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_explorer_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_miners_dream_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_miners_dream_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_extinct_junker_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_joyless_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_joyless_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_steelen_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_steelen_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_wheelbarrow_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_wheelbarrow_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_extinct_sludge_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_extinct_sludge_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_whitehole_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_whitehole_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_heavyweight_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_heavyweight_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_dissipated_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_dissipated_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_banana_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_banana_name`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.banana.b1.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_banana1`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.banana.b2.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_banana2`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.banana.b3.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_banana3`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.banana.b4.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_banana4`,[500])}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.banana.b5.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_banana5`,[50])}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_anarchist_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_anarchist_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_ascended_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_ascended_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_ascended_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_technophobe_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_technophobe_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_technophobe_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_iron_will_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`evo_challenge_cataclysm`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`space_red_ziggurat_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`tech_elerium_mining`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`tech_lasers`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`tech_generational_ship`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`wiki_resets_bioseed`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_failed_history_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`evo_challenge_cataclysm`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_lamentis_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_lamentis_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_soul_sponge_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_soul_sponge_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_nightmare_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_nightmare_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_escape_velocity_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_escape_velocity_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_endless_hunger_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_endless_hunger_name`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.endless_hunger.b1.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_endless_hunger1`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.endless_hunger.b2.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_endless_hunger2`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.endless_hunger.b3.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_endless_hunger3`,[80])}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.endless_hunger.b4.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_endless_hunger4`,[1200])}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.endless_hunger.b5.l ? `success` : `danger`}'},["'${loc(`wiki_achieve_endless_hunger5`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_gladiator_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_gladiator_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_what_is_best_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_what_is_best_name`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.warlord.k ? `success` : `danger`}'},["'${loc(`wiki_achieve_what_is_best_k`,[50])}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.warlord.p ? `success` : `danger`}'},["'${loc(`wiki_achieve_what_is_best_p`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.warlord.a ? `success` : `danger`}'},["'${loc(`wiki_achieve_what_is_best_a`,[250])}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.warlord.r ? `success` : `danger`}'},["'${loc(`wiki_achieve_what_is_best_r`)}'"])],
  [BIT('span',{'class': 'has-text-${global.stats.warlord.g ? `success` : `danger`}'},["'${loc(`wiki_achieve_what_is_best_g`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_pathfinder_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`evo_challenge_truepath`)}'"])],
  [BIT('span',{'class': "has-text-${global.stats.achieve['ashanddust'] ? 'success' : 'danger'}"},["'${loc(`wiki_resets_mad`)}'"])],
  [BIT('span',{'class': "has-text-${global.stats.achieve['exodus'] ? 'success' : 'danger'}"},["'${loc(`wiki_resets_bioseed`)}'"])],
  [BIT('span',{'class': "has-text-${global.stats.achieve['obsolete'] ? 'success' : 'danger'}"},["'${loc(`wiki_resets_ai`)}'"])],
  [BIT('span',{'class': "has-text-${global.stats.achieve['bluepill'] ? 'success' : 'danger'}"},["'${loc(`wiki_resets_matrix`)}'"])],
  [BIT('span',{'class': "has-text-${global.stats.achieve['retired'] ? 'success' : 'danger'}"},["'${loc(`wiki_resets_retired`)}'"])],
  [BIT('div',{},['\'${loc("achieve_perks_overlord1",[10])}\''])],
  [BIT('div',{},['\'${loc("achieve_perks_overlord2")}\''])],
  [BIT('div',{},['\'${loc("achieve_perks_overlord3")}\''])],
  [BIT('div',{},['\'${loc("achieve_perks_overlord4")}\''])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`achieve_overlord_name`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_genetic_memory_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_animus_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_divine_remembrance_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_divine_proportion_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_genetic_repository_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_spatial_reasoning_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_spatial_superiority_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_spatial_supremacy_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_dimensional_warping_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_morphogenesis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_recombination_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_homologous_recombination_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_genetic_reshuffling_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_recombinant_dna_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_chimeric_dna_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_molecular_cloning_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_transgenes_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_replication_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_enhanced_muscle_fiber_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_artificer_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_detail_oriented_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_rigorous_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_governance_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_synthesis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_karyokinesis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_cytokinesis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_hardened_genes_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_unlocked_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_universal_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_standard_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_mastered_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_ancients_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_faith_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_devotion_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_acolyte_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_conviction_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_negotiator_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_transcendence_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_geographer_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_architect_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_mitosis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_metaphase_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_mutation_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_transformation_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_metamorphosis_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_bleeding_effect_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_synchronicity_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_astral_awareness_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_bleeding_effect_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_blood_remembrance_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_blood_sacrifice_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_genepool_essence_absorber_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_purify_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_chum_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_lust_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_illuminate_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_greed_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_hoarder_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_artisan_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_attract_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_wrath_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_prepared_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_compact_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_unbound_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_unbound_resistance_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_shadow_war_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_unbound_immunity_title`)}'"])],
  [BIT('span',{'class': 'has-text-caution'},["'${loc(`arpa_blood_blood_aware_title`)}'"])],
  [BIT('div',{},['\'${loc("achieve_perks_novice",[rna,dna])}\'']), BIT('div',{},['\'${loc("achieve_perks_novice2")}\''])],
  [BIT('div',{},['\'${loc("achieve_perks_journeyman2",[rqueue,queue])}\'']), BIT('div',{},['\'${loc("achieve_perks_journeyman3")}\''])],
  [BIT('div',{},['\'${loc("achieve_perks_journeyman1",[1])}\'']), BIT('div',{},['\'${loc("achieve_perks_journeyman3")}\''])],
  [BIT('div',{'class': 'achievement'},[BIT('span',{'class': 'has-text-warning'},["'${perkList[perk].name}'"])])],
  [BIT('div',{'class': 'perk'},["'${subperk.desc()}'"])],
  [BIT('div',{'class': 'achievement'},[BIT('span',{'class': 'has-text-warning'},["'${perkList[perk].name}'"]), BIT('span',{},["'${perkList[perk].desc()}'"])])],
  [BIT('div',{'class': 'has-text-caution'},["'${loc(`perks_none`)}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-success'},['\'${loc("achieve_stats_overall")}\''])])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_plasmid_earned")}\'']), "' {{ s.plasmid | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_antiplasmid_earned")}\'']), "' {{ s.antiplasmid | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_phage_earned")}\'']), "' {{ s.phage | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_dark_earned")}\'']), "' {{ s.dark | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_harmony_earned")}\'']), "' {{ s.harmony | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_blood_earned")}\'']), "' {{ s.blood | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_artifact_earned")}\'']), "' {{ s.artifact | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_knowledge_spent")}\'']), "' {{ s.know | t_know | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_starved_to_death")}\'']), "' {{ s.starved | t_starved | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_died_in_combat")}\'']), "' {{ s.died | t_died | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_game_days_played")}\'']), "' {{ s.days | played | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_portals")}\'']), "' {{ s.portals | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_total_resets")}\'']), "' {{ s.reset | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_mad_resets")}\'']), "' {{ s.mad | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_bioseed_resets")}\'']), "' {{ s.bioseed | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_cataclysm_resets")}\'']), "' {{ s.cataclysm | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_blackhole_resets")}\'']), "' {{ s.blackhole | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_ascension_resets")}\'']), "' {{ s.ascend | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_descension_resets")}\'']), "' {{ s.descend | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_apotheosis_resets")}\'']), "' {{ s.apotheosis | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_aiappoc_resets")}\'']), "' {{ s.aiappoc | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_matrix_resets")}\'']), "' {{ s.matrix | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_retire_resets")}\'']), "' {{ s.retire | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_eden_resets")}\'']), "' {{ s.eden | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_terraform_resets")}\'']), "' {{ s.terraform | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_gecks")}\'']), "' {{ s.geck | format }}'"])],
  [BIT('div',{'class': 'cstat'},[BIT('span',{'class': 'has-text-success'},['\'${loc("achieve_stats_current_game")}\''])])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_knowledge_spent")}\'']), "' {{ s.know | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_starved_to_death")}\'']), "' {{ s.starved | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_died_in_combat")}\'']), "' {{ s.died | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_attacks_made")}\'']), "' {{ s.attacks | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_game_days_played")}\'']), "' {{ s.days | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_demons_kills")}\'']), "' {{ s.dkills | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_sacrificed")}\'']), "' {{ s.sac | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_murders")}\'']), "' {{ s.murders | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_psymurders")}\'']), "' {{ s.psykill | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_unstable")}\'']), "' {{ s.uDead | format }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_thermite")}\'']), "' {{ r.Thermite.amount | res }}'"])],
  [BIT('span',{},["'${trickOrTreat(7,12,true)}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_trickortreat")}\'']), "' {{ s.cfood | format }} ${trick}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_gods")}\'']), "' {{ g.gods | species }}'"])],
  [BIT('div',{},[BIT('span',{'class': 'has-text-warning'},['\'${loc("achieve_stats_old_gods")}\'']), "' {{ g.old_gods | species }}'"])],
]